[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
logfile_maxbytes=50MB
logfile_backups=10

[program:mariadb]
command=/usr/sbin/mariadbd --skip-ssl
user=mysql
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/mariadb.log
stderr_logfile=/var/log/supervisor/mariadb_error.log
priority=10

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/apache2.log
stderr_logfile=/var/log/supervisor/apache2_error.log
priority=20
