<?php
/**
 * LiquidGlass 主题配置项
 * 通用项（color / link_cols / modules / notice / gonganbei）保留，默认值贴合 Apple 生态；
 * 其余为风格增强项：壁纸、玻璃模糊、图标风格、外观模式、图标圆角。
 */
$theme_config = array(
    array(
        'type' => 'color',
        'name' => 'color',
        'title' => '强调色（系统蓝）',
        'description' => '用于选中态、开关、滑块与高亮描边，默认 iOS 系统蓝 #007AFF',
        'value' => '#007AFF',
        'verify' => '',
    ),
    array(
        'type' => 'select',
        'name' => 'link_cols',
        'title' => '每屏图标列数',
        'description' => 'PC 端窗口内的图标网格列数（移动端自动收敛为 4 列自适应）',
        'value' => '5',
        'enum' => array('3' => '3 列', '4' => '4 列', '5' => '5 列', '6' => '6 列'),
        'verify' => '',
    ),
    array(
        'type' => 'checkbox',
        'name' => 'modules',
        'title' => '桌面组件',
        'description' => '勾选需要在桌面组件区显示的模块（时钟 / 随机一言 / 公告 / 记事本 / 待办事项）',
        'value' => array('clock', 'note', 'yan', 'todo'),
        'enum' => array(
            'clock' => '时钟组件',
            'yan'   => '随机一言',
            'note'  => '公告组件',
            'notes' => '记事本',
            'todo'  => '待办事项',
        ),
        'verify' => '',
    ),
    array(
        'type' => 'textarea',
        'name' => 'notice',
        'title' => '桌面公告',
        'description' => '支持 HTML，会以玻璃卡片形式显示在桌面组件区',
        'value' => '',
        'verify' => '',
    ),
    array(
        'type' => 'text',
        'name' => 'gonganbei',
        'title' => '公安备案号',
        'description' => '如：京公网安备 11000000000000 号',
        'value' => '',
        'verify' => '',
    ),
    array(
        'type' => 'select',
        'name' => 'wall',
        'title' => '壁纸配色',
        'description' => '柔和渐变壁纸方案（薰衣草紫 / 天蓝 / 薄荷绿 混合为默认）',
        'value' => 'aurora',
        'enum' => array(
            'aurora'   => '极光（薰衣草紫 + 天蓝 + 薄荷绿）',
            'dusk'     => '暮色（藕粉 + 暖橙 + 淡紫）',
            'mint'     => '薄荷（青绿 + 天蓝 + 月白）',
            'graphite' => '石墨（中性灰 + 冷蓝，低饱和）',
        ),
        'verify' => '',
    ),
    array(
        'type' => 'select',
        'name' => 'blur',
        'title' => '玻璃模糊强度',
        'description' => 'Liquid Glass 材质的 backdrop-filter 模糊半径',
        'value' => 'medium',
        'enum' => array('soft' => '轻柔 12px', 'medium' => '标准 20px', 'strong' => '厚重 32px'),
        'verify' => '',
    ),
    array(
        'type' => 'radio',
        'name' => 'logo_type',
        'title' => 'LOGO模式',
        'description' => '电脑端顶部LOGO显示Apple标志或后台网站基本设置中的LOGO图片',
        'value' => 'apple',
        'enum' => array('apple' => 'Apple标志', 'logo' => '网站LOGO'),
        'verify' => '',
    ),
    array(
        'type' => 'select',
        'name' => 'icons',
        'title' => '图标风格',
        'description' => '图标底座材质：渐变 / 拟物 / 扁平 / 官方（纯色底 + 白色符号）',
        'value' => 'gradient',
        'enum' => array(
            'gradient' => '默认渐变',
            'skew'     => '高保真拟物',
            'flat'     => '扁平通透',
            'official' => '官方纯色',
        ),
        'verify' => '',
    ),
    array(
        'type' => 'radio',
        'name' => 'scheme',
        'title' => '外观模式',
        'description' => '跟随系统时，浅色为通透毛玻璃，深色为深色毛玻璃 + 深空灰背景',
        'value' => 'auto',
        'enum' => array('auto' => '跟随系统', 'light' => '始终浅色', 'dark' => '始终深色'),
        'verify' => '',
    ),
    array(
        'type' => 'select',
        'name' => 'icon_radius',
        'title' => '图标圆角',
        'description' => 'iOS 图标连续曲率近似值（百分比圆角）',
        'value' => '22',
        'enum' => array('16' => '16% 近方', '22' => '22% 标准 iOS', '28' => '28% 圆润', '50' => '50% 圆形'),
        'verify' => '',
    ),
    array(
        'type' => 'radio',
        'name' => 'suggestion',
        'title' => '搜索联想词',
        'description' => '在搜索框输入时调用百度联想词接口，下拉展示补全建议（默认开启；仅用百度一种，与所选引擎无关，仅作输入补全）',
        'value' => 'on',
        'enum' => array('on' => '开启', 'off' => '关闭'),
        'verify' => '',
    ),
);
return $theme_config;
