<?php
$theme_config = array(
    array(
        'type' => 'color',
        'name' => 'color',
        'title' => '主题主色（霓虹青）',
        'description' => '用于强调、描边与辉光，建议使用高饱和霓虹色',
        'value' => '#00f0ff',
        'verify' => '',
    ),
    array(
        'type' => 'select',
        'name' => 'link_cols',
        'title' => '链接列数',
        'description' => '右侧链接区每个分组每行展示的链接数量',
        'value' => '3',
        'enum' => array('3' => '3 列', '4' => '4 列', '5' => '5 列', '6' => '6 列'),
        'verify' => '',
    ),
    array(
        'type' => 'checkbox',
        'name' => 'modules',
        'title' => '首页模块',
        'description' => '勾选需要在控制台区显示的模块',
        'value' => array('clock'),
        'enum' => array('clock' => '霓虹时钟', 'yan' => '随机一言'),
        'verify' => '',
    ),
    array(
        'type' => 'textarea',
        'name' => 'notice',
        'title' => '首页公告',
        'description' => '支持 HTML，将显示在左侧控制台区',
        'value' => '',
        'verify' => '',
    ),
    array(
        'type' => 'text',
        'name' => 'gonganbei',
        'title' => '公安备案号',
        'description' => '如：京公网安备 11000000000000 号',
        'value' => '',
        'verify' => '',
    ),
    array(
        'type' => 'color',
        'name' => 'accent',
        'title' => '强调色（霓虹品红）',
        'description' => '用于第二辉光、分隔线与品牌标识',
        'value' => '#ff2e97',
        'verify' => '',
    ),
    array(
        'type' => 'radio',
        'name' => 'scanline',
        'title' => 'CRT 扫描线',
        'description' => '是否在全屏叠加复古显示器扫描线特效',
        'value' => 'on',
        'enum' => array('on' => '开启', 'off' => '关闭'),
        'verify' => '',
    ),
    array(
        'type' => 'radio',
        'name' => 'glow',
        'title' => '辉光强度',
        'description' => '链接与标题的霓虹辉光强弱',
        'value' => 'mid',
        'enum' => array('low' => '弱', 'mid' => '中', 'high' => '强'),
        'verify' => '',
    ),
);
return $theme_config;
